// <auto-generated />
using System;
using AnimeApi.Server.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimeApi.Server.DataAccess.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    [Migration("20260131194723_RemoveMysqlLeftovers")]
    partial class RemoveMysqlLeftovers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("English_Name");

                    b.Property<int>("Episodes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAiring")
                        .HasColumnType("timestamptz")
                        .HasColumnName("Finished_Airing");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Image_URL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Other_Name");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("Release_Year");

                    b.Property<decimal>("Score")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAiring")
                        .HasColumnType("timestamptz")
                        .HasColumnName("Started_Airing");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("TrailerEmbedUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Trailer_embed_url");

                    b.Property<string>("TrailerImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Trailer_image_url");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Trailer_url");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EnglishName" }, "Anime_English_Name_index");

                    b.HasIndex(new[] { "Episodes" }, "Anime_Episodes_index");

                    b.HasIndex(new[] { "Name" }, "Anime_Name_index");

                    b.HasIndex(new[] { "ReleaseYear" }, "Anime_Release_Year_index");

                    b.HasIndex(new[] { "Score" }, "Anime_Score_index");

                    b.HasIndex(new[] { "SourceId" }, "Anime_Source_Id_fk");

                    b.HasIndex(new[] { "TypeId" }, "Anime_Type_Id_fk");

                    b.ToTable("anime", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AnimeId" }, "AnimeId");

                    b.HasIndex(new[] { "GenreId" }, "GenreId");

                    b.ToTable("anime_genre", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeLicensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("LicensorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AnimeId" }, "AnimeId")
                        .HasDatabaseName("AnimeId1");

                    b.HasIndex(new[] { "LicensorId" }, "LicensorId");

                    b.ToTable("anime_licensor", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeProducer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProducerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AnimeId" }, "AnimeId")
                        .HasDatabaseName("AnimeId2");

                    b.HasIndex(new[] { "ProducerId" }, "ProducerId");

                    b.ToTable("anime_producer", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestampz")
                        .HasColumnName("Created_At");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Picture_Url");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("Role_Id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Favourite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("Anime_Id");

                    b.HasKey("UserId", "AnimeId");

                    b.HasIndex("AnimeId");

                    b.ToTable("user_favourites", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique();

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Licensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique()
                        .HasDatabaseName("Name1");

                    b.ToTable("licensor", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique()
                        .HasDatabaseName("Name2");

                    b.ToTable("producer", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestampz")
                        .HasColumnName("Created_At");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestampz")
                        .HasColumnName("Expires_At");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Hashed_Token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestampz")
                        .HasColumnName("Revoked_At");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "HashedToken" }, "Refresh_Token_Hashed_Token__index");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("Anime_Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created_At");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("UserId");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique()
                        .HasDatabaseName("Name3");

                    b.ToTable("source", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique()
                        .HasDatabaseName("Name4");

                    b.ToTable("type", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Anime", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Source", "Source")
                        .WithMany("Anime")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Anime_Source_Id_fk");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Type", "Type")
                        .WithMany("Anime")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("Anime_Type_Id_fk");

                    b.Navigation("Source");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeGenre", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Genre_ibfk_1");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Genre", "Genre")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Genre_ibfk_2");

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeLicensor", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("AnimeLicensors")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Licensor_ibfk_1");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Licensor", "Licensor")
                        .WithMany("AnimeLicensors")
                        .HasForeignKey("LicensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Licensor_ibfk_2");

                    b.Navigation("Anime");

                    b.Navigation("Licensor");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeProducer", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("AnimeProducers")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Producer_ibfk_1");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Producer", "Producer")
                        .WithMany("AnimeProducers")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Producer_ibfk_2");

                    b.Navigation("Anime");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AppUser", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Role_Id_fk");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Favourite", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("Favourites")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Favourites_Anime_Id_fk");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.AppUser", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Favourites_User_Id_fk");

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.RefreshToken", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.AppUser", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("AnimeApi.Server.Core.Objects.Models.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("RefreshToken_User_Id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Review", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("Reviews")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Id_fk");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.AppUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Id_Fk");

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Anime", b =>
                {
                    b.Navigation("AnimeGenres");

                    b.Navigation("AnimeLicensors");

                    b.Navigation("AnimeProducers");

                    b.Navigation("Favourites");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AppUser", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Genre", b =>
                {
                    b.Navigation("AnimeGenres");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Licensor", b =>
                {
                    b.Navigation("AnimeLicensors");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Producer", b =>
                {
                    b.Navigation("AnimeProducers");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Source", b =>
                {
                    b.Navigation("Anime");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Type", b =>
                {
                    b.Navigation("Anime");
                });
#pragma warning restore 612, 618
        }
    }
}
