// <auto-generated />
using System;
using AnimeApi.Server.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimeApi.Server.DataAccess.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    partial class AnimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("English_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Episodes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Finished_Airing")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Image_URL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("utf8mb3_general_ci");

                    b.Property<string>("Other_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("utf8mb3_general_ci");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Release_Year")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Started_Airing")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("utf8mb3_general_ci");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .UseCollation("utf8mb3_general_ci");

                    b.Property<string>("Trailer_embed_url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Trailer_image_url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Trailer_url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "English_Name" }, "Anime_English_Name_index");

                    b.HasIndex(new[] { "Episodes" }, "Anime_Episodes_index");

                    b.HasIndex(new[] { "Name" }, "Anime_Name_index");

                    b.HasIndex(new[] { "Release_Year" }, "Anime_Release_Year_index");

                    b.HasIndex(new[] { "Score" }, "Anime_Score_index");

                    b.HasIndex(new[] { "SourceId" }, "Anime_Source_Id_fk");

                    b.HasIndex(new[] { "TypeId" }, "Anime_Type_Id_fk");

                    b.ToTable("anime", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AnimeId" }, "AnimeId");

                    b.HasIndex(new[] { "GenreId" }, "GenreId");

                    b.ToTable("anime_genre", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeLicensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("LicensorId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AnimeId" }, "AnimeId")
                        .HasDatabaseName("AnimeId1");

                    b.HasIndex(new[] { "LicensorId" }, "LicensorId");

                    b.ToTable("anime_licensor", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeProducer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProducerId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AnimeId" }, "AnimeId")
                        .HasDatabaseName("AnimeId2");

                    b.HasIndex(new[] { "ProducerId" }, "ProducerId");

                    b.ToTable("anime_producer", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestampz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Picture_Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("Role_Id");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Favourite", b =>
                {
                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Anime_Id")
                        .HasColumnType("integer");

                    b.HasKey("User_Id", "Anime_Id")
                        .HasName("PRIMARY");

                    b.HasIndex("Anime_Id");

                    b.ToTable("user_favourites", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique();

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Licensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("utf8mb3_general_ci");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique()
                        .HasDatabaseName("Name1");

                    b.ToTable("licensor", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("utf8mb3_general_ci");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique()
                        .HasDatabaseName("Name2");

                    b.ToTable("producer", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestampz");

                    b.Property<DateTime>("Expires_At")
                        .HasColumnType("timestampz");

                    b.Property<string>("Hashed_Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("Revoked_At")
                        .HasColumnType("timestampz");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("User_Id")
                        .IsUnique();

                    b.HasIndex(new[] { "Hashed_Token" }, "Refresh_Token_Hashed_Token__index");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anime_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .UseCollation("utf8mb3_general_ci");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("Anime_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique()
                        .HasDatabaseName("Name3");

                    b.ToTable("source", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Name")
                        .IsUnique()
                        .HasDatabaseName("Name4");

                    b.ToTable("type", (string)null);
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Anime", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Source", "Source")
                        .WithMany("Animes")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Anime_Source_Id_fk");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Type", "Type")
                        .WithMany("Animes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("Anime_Type_Id_fk");

                    b.Navigation("Source");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeGenre", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("Anime_Genres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Genre_ibfk_1");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Genre", "Genre")
                        .WithMany("Anime_Genres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Genre_ibfk_2");

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeLicensor", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("Anime_Licensors")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Licensor_ibfk_1");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Licensor", "Licensor")
                        .WithMany("Anime_Licensors")
                        .HasForeignKey("LicensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Licensor_ibfk_2");

                    b.Navigation("Anime");

                    b.Navigation("Licensor");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AnimeProducer", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("Anime_Producers")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Producer_ibfk_1");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Producer", "Producer")
                        .WithMany("Anime_Producers")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Producer_ibfk_2");

                    b.Navigation("Anime");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AppUser", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Role_Id_fk");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Favourite", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("Favourites")
                        .HasForeignKey("Anime_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Favourites_Anime_Id_fk");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.AppUser", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Favourites_User_Id_fk");

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.RefreshToken", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.AppUser", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("AnimeApi.Server.Core.Objects.Models.RefreshToken", "User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("RefreshToken_User_Id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Review", b =>
                {
                    b.HasOne("AnimeApi.Server.Core.Objects.Models.Anime", "Anime")
                        .WithMany("Reviews")
                        .HasForeignKey("Anime_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Anime_Id_fk");

                    b.HasOne("AnimeApi.Server.Core.Objects.Models.AppUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Id_Fk");

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Anime", b =>
                {
                    b.Navigation("Anime_Genres");

                    b.Navigation("Anime_Licensors");

                    b.Navigation("Anime_Producers");

                    b.Navigation("Favourites");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.AppUser", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Genre", b =>
                {
                    b.Navigation("Anime_Genres");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Licensor", b =>
                {
                    b.Navigation("Anime_Licensors");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Producer", b =>
                {
                    b.Navigation("Anime_Producers");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Source", b =>
                {
                    b.Navigation("Animes");
                });

            modelBuilder.Entity("AnimeApi.Server.Core.Objects.Models.Type", b =>
                {
                    b.Navigation("Animes");
                });
#pragma warning restore 612, 618
        }
    }
}
